# Generated by Django 5.2.3 on 2025-07-09 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('user_type', models.CharField(choices=[('patient', 'Paciente'), ('caregiver', 'Cuidador')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverPatientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuidados', to='api.firebaseuser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuidadores', to='api.firebaseuser')),
            ],
        ),
    ]
